feat: drag container
wafflestudio/interactive-web-client pull request #57
Opened 2023-04-09 11:27 UTC by andhl204

pixi를 이용할 때 Container(텍스트 + 배경)을 함께 드래그하는 방식을 추가했습니다.
기존의 drag.ts에 코드 추가했고 PixiCanvas.tsx도 약간 수정했는데, 이 방식이 괜찮을 것 같으면 파일 다시 정리하겠습니다:)

2023-04-22 12:41 UTC, designDefined requested changes

2023-04-22 12:41 UTC, designDefined commented on components/Editor/PixiCanvas/drag.ts
>  interface Draggable extends PIXI.Sprite {
요거 이름 SpriteDraggable로 바꾸면 좋을 듯!

2023-04-22 12:41 UTC, designDefined commented on components/Editor/PixiCanvas/drag.ts
>  export const onDragStart = (event: PIXI.InteractionEvent) => {
이벤트 핸들러들도 앞에 sprite 붙여서 통일시키기!

2023-04-26 09:15 UTC, TheoLee72 commented on components/Editor/PixiCanvas/drag.ts
>    }
Container는 지금 잘 되는데 Sprite가 잘 안되네요;; Sprite는 마우스가 경계를 만나면 그냥 초기 좌표로 돌아가버리네요. 똑같은 방식으로 했는데 Container는 되고 Sprite가 안되는 이유를 아직은 잘 모르겠습니다. 좀 더 알아보겠습니다.

2023-04-26 14:33 UTC, andhl204 commented on components/Editor/PixiCanvas/PixiCanvas.tsx
> +    <Stage onMouseOut={borderBarrier}>
```typescript
<Stage
  onMouseOut={() => setGlobalMouse(true)}
  onMouseEnter={() => setGlobalMouse(false)}
>
```
이렇게 하면 borderBarrier 함수 없이(drag 관련 함수들 내부에서도 globalMouse 속성만 가지고) 처리할 수 있을 것 같은데 어떤가요??

2023-04-26 14:33 UTC, andhl204 commented on components/Editor/PixiCanvas/drag.ts
> +    if (globalMouse == true)
마우스를 정말 빨리 움직이면 dragEnd가 호출되기 전에 오브젝트가 stage 바깥으로 나가버리는데 이 경우에 position 다시 조정하는 함수 추가해도 좋을 것 같아요. 
```typescript
if (object.x < -1*object.width) object.x = -1*object.width + 10
```
(요런 느낌..?)

2023-04-26 14:35 UTC, andhl204 commented on components/Editor/PixiCanvas/drag.ts
>    }
이거 지금 globalMouse 속성이 변할 때마다 Stage가 리렌더되는 방식이라 초기화돼서 Sprite는 원래대로 돌아가는 거 같아요. Container가 안돌아가는게 오히려 좀 이상하긴 한데 스토어랑 연결되면 위치를 저장할 수 있으니 해결될 듯 합니다..!

2023-04-29 13:12 UTC, andhl204 commented
@TheoLee72 아까 화면공유때는 문제 없었던 것 같아서 기능적인 부분에 대해서는 슬랙에 간단하게 잘 안되는 부분 남겼습니다.
코드 스타일은 혹시 prettier 파일이 잘 적용되어 있는지 확인해보셨나요??

2023-04-29 16:37 UTC, designDefined approved these changes

2023-04-29 17:09 UTC, designDefined requested changes
저도 확인했습니당~~ 승원이 제보한 에러 + 추가적으로 발견한 에러 하나 슬랙에다 적어놓았습니다!!
그냥 코드 구현 궁금한 부분 하나 코멘트 달아놨슴다 아무나 대답해주시면 감사...ㅎㅎ

2023-04-29 17:09 UTC, designDefined commented on components/Editor/PixiCanvas/drag.ts
> +  object.data = event.data;
그냥 궁금증인데 혹시 이 object.data가 하는 일이 무엇일까요??? 용도가 있다면 주석으로 간단히 적어주면 좋을 듯 합니당

2023-04-29 17:11 UTC, designDefined requested changes
빼놓은 거 추가 (디버그 관련)

2023-04-29 17:11 UTC, designDefined commented on components/Editor/PixiCanvas/PixiCanvas.tsx
> +    mouseup={onSpriteDragEnd}
아마 이 부분을 다르게 구현해야 mouseup이 다른 오브젝트 위나 화면 바깥에도 잘 감지되지 않을까요....? 저도 고민 좀 해보겠슴다

2023-05-13 12:11 UTC, designDefined approved these changes
LGTM

2023-05-13 12:11 UTC, merged